### ISSUE TITLE
markdown-mode hangs Emacs

### ISSUE THREAD

**Issue by alecigne** [jrblevin/markdown-mode#44]
Hi,

I work on a fairly large markdown file (126k) and commit 86e0c76 (from Dec 16) hangs Emacs regularly (it lags when I type fast, lags when I use `scroll-up-command` or `scroll-down-command`, etc.). Everything works fine with the previous commit. I also tried with a minimal init file, only requiring `markdown-mode`, and the problem is the same.

I'd like to be able to provide more details here but I don't know how to proceed.

Thank you

**Comment by jrblevin** [comment]
Thanks for your report. I am aware that are some issues with lag and hanging, particularly with very large files, and I am actively looking into it. (See also #30 and #42.) This should be helpful in isolating at least one of the issues.

**Comment by hut8** [comment]
I'm getting this also. Mine file is very small. Looking around briefly it appears this happens on all files. I just upgraded this morning. If I can be of more help, please let me know.

**Comment by jrblevin** [comment]
Can you check to see whether the recent commits improved things?

**Comment by alecigne** [comment]
I have no quantitative data but I think it's better now. It doesn't hang when using `scroll-up-command` and `scroll-down-command` anymore. However, the lag when typing fast is still here.

**Comment by jrblevin** [comment]
Thanks for checking! I used the profiler to scroll through a large (> 5000 line) file and it is now much faster for me. I didn't check typing. Parsing Markdown accurately and in real time is difficult, but I will keep working to make it more efficient. I will try profiling when entering text into a large file as well to see where the bottlenecks are.

**Comment by jrblevin** [comment]
Further profiling revealed that the insertion lag was mostly due to the after-change hook that performs wiki link fontification. I will have a patch ready soon that substantially speeds things up!

**Comment by hut8** [comment]
Works great for me now. Thanks very much!

**Comment by jrblevin** [comment]
@hut8 Great—I'm glad it's work better now.

@alecigne I just saw your edit. It does make sense that it could be better or worse depending on the surrounding context. Some regions may be more difficult to parse than others. When you insert characters, things have to be parsed again in case the syntax changed.

I just pushed commit acf7c5e which I think should essentially eliminate the lag when typing. Please let me know if not. For me, this makes any lag almost imperceptible in my 5000+ line file, but if it doesn't work for you then I may ask for a more specific test case.

Another thing you can do to increase performance is to set `markdown-make-gfm-checkboxes-buttons` to `nil`. When this is non-`nil`, `markdown-mode` must check all input for checkboxes.

**Comment by alecigne** [comment]
Hi,

Thank you for looking into this. Commit `acf7c5e` doesn't fix the lagging problem. My file is actually my PhD thesis and thus contains a LOT of references in the format:

    [@chow2012]

or

    [@goldberg2008; @pajerowski2007]

That may be the source of the problem. This is a format understood by `pandoc-citeproc`. If you give me some time, I will try and build an example file in which the problem is present, since I don't want to send you my thesis ;)

As for now, I will continue to use markdown-mode under version `01dc652`.

**Comment by jrblevin** [comment]
One option is to obfuscate your thesis while preserving the syntax. Then I could see first hand what is happening. If you are on Linux or OS X, may I suggest using `tr` to randomly scramble the letters while leaving the symbols, markup, and punctuation intact? Here's one suggestion:

```
cat thesis.md | tr '[a-zA-Z]' 'x' | tr '[0-9]' '1' > scramble.md
```

It translates all letters to 'x' and all numbers to '1'. If thats sufficiently obfuscated, then you could email the file to me at <jrblevin@sdf.org>.

**Comment by jrblevin** [comment]
I have also created a new branch to help us diagnose the problem without disturbing the main branch: https://github.com/jrblevin/markdown-mode/tree/diagnose-44

There are two commits of interest right now. Both are based on the current `HEAD`.
1. Commit c428fe9 reverts back to the old extend-region function from the "good" commit 01dc652.
2. Commit a8af698 is (another) alternative extend-region function that I'd like to test.

Could you check number 2 first and if that doesn't work, also try number 1? Thanks for your patience while we narrow this down.

**Comment by alecigne** [comment]
Hi,

The new version of the function (commit a8af698) fix the lagging problem. For what it's worth, c428fe9 does as well.

My thesis is indeed in French, and is about biology – so in a way it is already pretty well obfuscated! But all jokes aside if you still need the file despite the new working function, let me know and I will send it to you.

Again, thank you for your quick response.

**Comment by jrblevin** [comment]
Excellent! Likewise, thanks for testing out these changes so quickly and helping improve markdown-mode! Good luck with your thesis—it's an honor that you're writing it in markdown-mode. Let me know if you have any other issues.
